### ISSUE TITLE
GeoTrellis Temporal Layers potential issue on the unix times borders

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-server#248]
The task is to find the cause of a bug (time boxed(?) would be re estimated after it would be clear what happened).

The stacktrace:

```
java.lang.IllegalArgumentException: requirement failed: NOT: 5270498310033961778 < 3259806592
        at scala.Predef$.require(Predef.scala:281)
        at geotrellis.store.index.zcurve.Z3Range.<init>(Z3Range.scala:23)
        at geotrellis.store.index.zcurve.Z3$.zranges(Z3.scala:114)
        at geotrellis.store.index.zcurve.ZSpaceTimeKeyIndex.indexRanges(ZSpaceTimeKeyIndex.scala:70)
        at geotrellis.store.s3.S3CollectionLayerReader.$anonfun$read$3(S3CollectionLayerReader.scala:67)
```

The layer has the following temporal slices: `["1960-01-01T12:00Z","1974-01-01T12:00Z"]`

Its metadata:
```javascript
{
	"name": "layert",
	"zoom": 14
}, {
	...,
	"metadata": {
		"extent": {
			"xmin": -8841760.937236203,
			"ymin": 5431647.838449555,
			"xmax": -8809758.671160765,
			"ymax": 5458769.788136984
		},
		"layoutDefinition": {
			"extent": {
				"xmin": -20037508.342789244,
				"ymin": -20037508.342789244,
				"xmax": 20037508.342789244,
				"ymax": 20037508.342789244
			},
			"tileLayout": {
				"layoutCols": 16384,
				"layoutRows": 16384,
				"tileCols": 256,
				"tileRows": 256
			}
		},
		"bounds": {
			"minKey": {
				"col": 4577,
				"row": 5960,
				"instant": -315576000000
			},
			"maxKey": {
				"col": 4590,
				"row": 5971,
				"instant": 126273600000
			}
		},
		"cellType": "uint8",
		"crs": "+proj=merc ... "
	},
	"keyIndex": {
		"type": "zorder",
		"properties": {
			"keyBounds": {
				"minKey": {
					"col": 0,
					"row": 0,
					"instant": -1892576000000
				},
				"maxKey": {
					"col": 2147483647,
					"row": 2147483647,
					"instant": 630624000000
				}
			},
			"temporalResolution": 31536000000
		}
	}
```

As we can notice from the metadata above `z` coord (`instant`) is overloaded in the `metadata.bounds` field. This could lead to a potential issues with generation `ZCurve` ranges out of the unix time bounds.

If by the end of this issue we would confirm that the problem is only that GeoTrellis `ZCurve` can't work outside of the unix time bounds, we'll move it to the geotrellis core repo.

**Comment by pomadchin** [comment]
The code to reproduce it:

```scala
import geotrellis.layer.{KeyBounds, SpaceTimeKey}
import geotrellis.store.index.zcurve.ZSpaceTimeKeyIndex
import org.scalatest.{FunSpec, Matchers}

class Z3Spec extends FunSpec with Matchers {
  describe("Z3 specs") {
    // https://github.com/geotrellis/geotrellis-server/issues/248
    it("should generate ranges correct") {
      val temporalResolution: Long = 31536000000L
      val minKey = SpaceTimeKey(4577, 5960, instant = -315576000000L)
      val maxKey = SpaceTimeKey(4590, 5971, instant = 126273600000L)
      val kb = KeyBounds(minKey, maxKey)
      val index = new ZSpaceTimeKeyIndex(kb, temporalResolution)

      index.indexRanges(minKey -> maxKey)
    }
  }
}
```

Which indeed fails with 

```scala
[info] - should generate ranges correct *** FAILED ***
[info]   java.lang.IllegalArgumentException: requirement failed: NOT: 5270498515401753889 < 208627606362
[info]   at scala.Predef$.require(Predef.scala:281)
[info]   at geotrellis.store.index.zcurve.Z3Range.<init>(Z3Range.scala:23)
[info]   at geotrellis.store.index.zcurve.Z3$.zranges(Z3.scala:114)
[info]   at geotrellis.store.index.zcurve.ZSpaceTimeKeyIndex.indexRanges(ZSpaceTimeKeyIndex.scala:70)
[info]   at geotrellis.store.query.Z3Spec.$anonfun$new$2(Z3Spec.scala:17)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

I guess this is definitely a Z3 limitation ):

**Comment by pomadchin** [comment]
I'll move it into geotrellis core tomorrow.

**Comment by pomadchin** [comment]
We did a bit more of a research and came up with https://github.com/locationtech/geotrellis/pull/3224.

The workaround to this issue can be the layer ingest with a custom index defined: https://github.com/locationtech/geotrellis/pull/3224/files#diff-e33e0f8cacade3262fcaacf87dd1da88R98

@jfbourgon Let me know if you need some help with defining it; 

There is a bit outdated information in docs how to define it https://geotrellis.readthedocs.io/en/latest/guide/extending-geotrellis.html#custom-keyindexes 

But basically you need to copy all the new code, define a KeyIndexRegistrator and register it in the [application.conf](https://github.com/locationtech/geotrellis/blob/a659eca393901cf6a57a036b87c71bf1fc9f8fff/store/src/test/resources/reference.conf#L15)
